site_name: Pars Documentation
site_url: https://docs.parsdevkit.net/
site_description: Pars Documentation
repo_url: https://github.com/parsdevkit/pars
repo_name: parsdevkit/pars
edit_uri: edit/main/docs/contents/
docs_dir: contents
nav:
  - Home: index.md
  - Getting started:
    - Overview: 
      - getting-started/concept/index.md
      - Workspace: getting-started/concept/workspace.md
      - Group: getting-started/concept/group.md
      - Project: 
        - Project: getting-started/concept/project.md
        - Application Project: getting-started/concept/application-project.md
      - Resource: 
        - Resource: getting-started/concept/resource.md
        - Object Resource: getting-started/concept/object-resource.md
        - Data Resource: getting-started/concept/data-resource.md
      - Template:
        - Template: getting-started/concept/template.md
        - Shared Template: getting-started/concept/shared-template.md
        - Code Template: getting-started/concept/code-template.md
        - File Template: getting-started/concept/file-template.md
      # - Task: getting-started/concept/task.md
    # - Workflow: 
    #   - getting-started/workflow/index.md
    #   - Project Organization: getting-started/workflow/project-organization.md
    #   - Code Generation: getting-started/workflow/code-generation.md
    #   - Build Manager: getting-started/workflow/build-manager.md
  - Guides:
    # - guides/index.md
    - Commands: 
      - guides/commands/index.md
      - environment: 
        - guides/commands/environment/index.md
        - environment list: guides/commands/environment/list.md
      - init: guides/commands/init/index.md
      - workspace: 
        - guides/commands/workspace/index.md
        - workspace list: guides/commands/workspace/list.md
        - workspace describe: guides/commands/workspace/describe.md
        - workspace remove: guides/commands/workspace/remove.md
      - group: 
        - guides/commands/group/index.md
        - group submit: guides/commands/group/submit.md
        - group list: guides/commands/group/list.md
        - group describe: guides/commands/group/describe.md
        - group remove: guides/commands/group/remove.md
      - project: 
        - guides/commands/project/index.md
        - project submit: guides/commands/project/submit.md
        - project list: guides/commands/project/list.md
        - project describe: guides/commands/project/describe.md
        - project remove: guides/commands/project/remove.md
      - resource: 
        - guides/commands/resource/index.md
        - resource submit: guides/commands/resource/submit.md
        - resource list: guides/commands/resource/list.md
        - resource remove: guides/commands/resource/remove.md
      - template: 
        - guides/commands/template/index.md
        - template submit: guides/commands/template/submit.md
        - template list: guides/commands/template/list.md
        - template remove: guides/commands/template/remove.md
      # - task: guides/commands/task/index.md
      # - guides/commands/browse/index.md
      # - guides/commands/build/index.md
      # - guides/commands/test/index.md
      # - guides/commands/clean/index.md
      # - guides/commands/release/index.md
      # - guides/commands/distribute/index.md
      # - guides/commands/execute/index.md
      # - guides/commands/info/index.md
      # - guides/commands/open/index.md
      - completion: 
        - guides/commands/completion/index.md
        - completion bash: guides/commands/completion/bash.md
        - completion powershell: guides/commands/completion/powershell.md
        - completion fish: guides/commands/completion/fish.md
        - completion zsh: guides/commands/completion/zsh.md
    - Schemas: 
      - guides/schemas/index.md
      - General:
        - Yaml Specifications: guides/schemas/general/yaml-specifications.md
        - Log Level Enum: guides/schemas/enum/logLevelEnum.md
        - Workspace View Types Enum : guides/schemas/enum/workspaceViewTypesEnum.md
      - Group: guides/schemas/object/group/group-object-model.md
      - Projects: 
        - Application Project: guides/schemas/object/project/application-project-object-model.md
      - Resources: 
        - Object Resource: 
          - Object Resource: guides/schemas/object/resource/object-resource-object-model.md
          - Data Type: guides/schemas/object/resource/data-type-object-model.md
        - Data Resource: guides/schemas/object/resource/data-resource-object-model.md
      - Templates: 
        - Shared Template:
          - Shared Template: guides/schemas/object/template/shared-template-object-model.md
          # - Design: guides/schemas/object/template/shared-template-design.md
          # - Context: guides/schemas/object/template/shared-template-context-object.md
          # - Functions: guides/schemas/object/template/shared-template-functions.md

        - Code Template:
          - Code Template: guides/schemas/object/template/code-template-object-model.md
          - Design: guides/schemas/object/template/code-template-design.md
          - Context: guides/schemas/object/template/code-template-context-object.md
          - Functions: guides/schemas/object/template/code-template-functions.md

        - File Template: 
          - File Template: guides/schemas/object/template/file-template-object-model.md
          # - Design: guides/schemas/object/template/file-template-design.md
          # - Context: guides/schemas/object/template/file-template-context-object.md
          # - Functions: guides/schemas/object/template/file-template-functions.md

      # - Tasks: guides/schemas/object/task/task-object-model.md
    - Components: 
      # - guides/components/index.md
      - Templates:
        - Syntax: guides/components/templates/syntax.md
        - Functions: guides/components/templates/functions.md
        - Context: guides/components/templates/context.md
    - References: 
      - guides/references/literals.md
      - guides/references/data-structures.md
      - guides/references/value-types.md
  - Setup:
    - setup/index.md
    - Installation: setup/installation/installation.md
    - Downloads: setup/downloads/latest.md
    - Changelogs:
      - setup/changelogs/index.md
      - v1.0.2: setup/changelogs/v1.0.2.md
      - v1.0.1: setup/changelogs/v1.0.1.md
      - v1.0.0: setup/changelogs/v1.0.0.md
    - Configuration: setup/configuration/configuration.md
    - Upgrade: 
      - Upgrade: setup/upgrade/upgrade.md
      - 0.x to 1.x: setup/upgrade/upgrade-0xto1x.md
    - Backup: /
    - Restore: /
  - Extensions:
    # - extensions/index.md
    - Platforms: 
      - extensions/platforms/index.md
      - Dotnet: extensions/platforms/dotnet.md
      - GO: extensions/platforms/go.md
      - NodeJS: extensions/platforms/nodejs.md
      - Angular: extensions/platforms/angular.md
    - Languages: 
      - extensions/languages/index.md
      - C#: extensions/languages/csharp.md
      - Go: extensions/languages/go.md
      - TypeScript: extensions/languages/typescript.md
      - JavaScript: extensions/languages/javascript.md
    # - Providers: extensions/providers/index.md
    # - Modules: extensions/modules/index.md
    # - Plugins: extensions/plugins/index.md
    # - Packages: extensions/packages/index.md
  - Advanced:
    - advanced/index.md
    - Use Cases: 
      - advanced/use-cases/index.md
    - Best Practices: 
      - advanced/best-practices/index.md
    - Advanced Usage: 
      - advanced/advanced-usage/index.md
      - Autocompletion and Filtering:
        - Workspaces: advanced/advanced-usage/autocompletion-and-filtering/workspaces.md
        - Groups: advanced/advanced-usage/autocompletion-and-filtering/groups.md
        - Resources: advanced/advanced-usage/autocompletion-and-filtering/resources.md
        - Templates: advanced/advanced-usage/autocompletion-and-filtering/templates.md
        - Commands: advanced/advanced-usage/autocompletion-and-filtering/commands.md
        - Paths: advanced/advanced-usage/autocompletion-and-filtering/paths.md
        - Enumerations: advanced/advanced-usage/autocompletion-and-filtering/enumerations.md
  # - Contributing:
  #   - contributing/index.md
  - Extras:
    - Glossary: extras/glossary.md
    - Tags: extras/tags.md
    - Terms: extras/terms.md
    - References: extras/references.md
    - Samples: 
      - Application Projects : extras/samples/application-project/index.md

theme:
  name: material
  analytics:
    provider: google
    property: G-TNGBBETP6J
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://github.com/parsdevkit/pars/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.

  language: en
  custom_dir: theme
  favicon: assets/favicon.png
  font:
    code: Roboto Mono
  icon:
    logo: material/access-point
    annotation: material/arrow-right-circle-outline
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/git-alt
    edit: material/pencil 
    view: material/eye
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    tag:
      default: fontawesome/solid/tag
      html5: fontawesome/brands/html5
      javascript: fontawesome/brands/js
      css: fontawesome/brands/css3
      php: fontawesome/brands/php
  features:
    - header.autohide
    - navigation.top
    - navigation.footer
    # - navigation.instant
    # - navigation.instant.progress
    # - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    # - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    # - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    # - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - content.code.select
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
plugins:
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
  - i18n:
      docs_structure: folder
      default_language: en
      material_alternate: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: "Pars Documentation"
          site_description: "Pars Documentation"
        # - locale: tr
        #   name: Türkçe
        #   build: true
        #   site_name: "Pars Dökümantasyon"
        #   site_description: "Pars Dökümantasyon"
        #   nav_translations:
        #     Code Blocks: Kod Blok
        #     Guides: Klavuz
        # - locale: ar
        #   name: عربي
        #   build: true
        #   site_name: "توثيق Pars"
        #   site_description: "توثيق Pars"
        #   nav_translations:
        #     Guides: خطوط إرشاد
        # - locale: ru
        #   name: Русский
        #   build: true
        #   site_name: "Документация Pars"
        #   site_description: "Документация Pars"
        #   nav_translations:
        #     Guides: Путеводители
        # - locale: de
        #   name: Deutsch
        #   build: true
        #   site_name: "Pars-Dokumentation"
        #   site_description: "Pars-Dokumentation"
        #   nav_translations:
        #     Guides: Benutzerhandbücher
        # - locale: fr
        #   name: Français
        #   build: true
        #   site_name: "Documentation Pars"
        #   site_description: "Documentation Pars"
        #   nav_translations:
        #     Guides: Guides de l'utilisateur
        # - locale: es
        #   name: Español
        #   build: true
        #   site_name: "Documentación de Pars"
        #   site_description: "Documentación de Pars"
        #   nav_translations:
        #     Guides: Guías
        # - locale: pt
        #   name: Português
        #   build: true
        #   site_name: "Documentação Pars"
        #   site_description: "Documentação Pars"
        #   nav_translations:
        #     Guides: Guias
        # - locale: ja
        #   name: 日本語
        #   build: true
        #   site_name: "Pars ドキュメント"
        #   site_description: "Pars ドキュメント"
        #   nav_translations:
        #     Guides: ガイド
        # - locale: zh
        #   name: 中国人
        #   build: true
        #   site_name: "Pars 文档"
        #   site_description: "Pars 文档"
        #   nav_translations:
        #     Guides: 指南
  - info:
      enabled: false
  # - autorefs:
  # - group:
  #     enabled: !ENV CI
  # - optimize
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
  # - meta:
      # meta_file: .meta.yml
  #     enabled: false
  # - redirects
  - offline
  - mermaid2
  - tags:
      tags_file: extras/tags.md
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang: 
        - en
        - tr
  # - social
  # - blog
  # - glightbox
  - privacy:
      enabled: !ENV [CI, false]
  # - git-revision-date-localized:
  #     enable_creation_date: true
  # - git-committers:
  #     repository: parsdevkit/pars
  #     branch: main
  # - git-authors
  - ezglossary:
      markdown_links: true
      list_definitions: false
      # use_default: true
      tooltip: full
      inline_refs: short
      # sections:
      #   - terms
      #   - demo

hooks:
  - theme/hooks/shortcodes.py
  - theme/hooks/socialmedia.py
extra:
  homepage: http://docs.parsdevkit.net/
  version:
    provider: mike
    default: latest
    alias: true
  status:
    new: Recently added
    deprecated: Deprecated
  scope: /
  tags:
    html5: html5
    HTML5: html5
    JavaScript: javascript
    javascript: javascript
    css: css
    CSS: css
    CSS3: css
    PHP: php
    php: php
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:info@parsdevkit.net
    - icon: fontawesome/brands/github 
      link: https://github.com/parsdevkit/pars
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/groups/13072322/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@ParsDevKit
    - icon: fontawesome/brands/medium
      link: https://medium.com/@parsdevkit
  generator: false
  consent:
    title: Cookie consent
    actions:
      - accept
      - reject
      - manage
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
copyright: >
  Copyright &copy; 2017 - 2024 Pars –
  <a href="#__consent">Change cookie settings</a>
markdown_extensions:
  # Python Markdown
  # - mdx_spanner
  # - codeblockheader
  - abbr
  - admonition
  - attr_list
  - wikilinks:
      # wiki_base_url: http://google.com
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: "#"
      # baselevel: 2
      # separator: "_"
      title: On this page
      # toc_depth: 3
      permalink_title: Anchor link to this section for reference
      # slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower

  # Python Markdown Extensions
  # - pymdownx.blocks.admonition
  # - pymdownx.blocks.define
  # - pymdownx.blocks.details
  # - pymdownx.blocks.tab
  # - pymdownx.blocks.html
  - pymdownx.saneheaders
  - pymdownx.progressbar
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
      # auto_title: true
      # linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.magiclink:
      repo_url_shortener: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        # - name: prefix
        #   class: prefix
        #   format: !!python/name:custom_doc_tools.superfences.prefix_code_format
        # - name: diagram
        #   class: diagram
        #   format: !!python/name:pymdownx.superfences.fence_code_format
        # - name: math
        #   class: arithmatex
        #   format: !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {kwds: {mode: generic, tag: pre}}
        # - name: md-render
        #   class: md-render
        #   format: !!python/name:tools.pymdownx_md_render.md_sub_render
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
      # clickable_checkbox: true
  - pymdownx.critic:
      mode: view
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
        - includes/mkdocs.md
extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/custom.css
extra_javascript:
  # - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  # - assets/javascripts/tablesort.js
  - assets/javascripts/mathjax.js
watch:
  - includes
  - theme
# use_directory_urls: true